/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_ad08;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author i_rom
 */
public class PanelPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlimentos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMenu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaComida = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonAnadirMenu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombreAlimento_in = new javax.swing.JTextField();
        botonBuscarAlimento = new javax.swing.JButton();
        botonAmadirAlimento = new javax.swing.JButton();
        borrarAlimentos = new javax.swing.JButton();
        caloriasAlimento_in = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBorrarComida = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuAnadirComida = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuBucarAlimento = new javax.swing.JMenuItem();
        anadirAlimentosMenu = new javax.swing.JMenuItem();
        borrarMenuAlimentos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        nuevoMenu = new javax.swing.JMenuItem();
        borraralimentoMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Diario");

        tablaAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tablaAlimentos);

        tablaMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(tablaMenu);

        tablaComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tablaComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaComidaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaComida);

        jLabel1.setText("Comidas");

        jLabel2.setText("Menú");

        jLabel3.setText("Alimentos");

        botonAnadirMenu.setText("Añadir Alimento");
        botonAnadirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnadirMenuActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre");

        jLabel7.setText("Calorias");

        nombreAlimento_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAlimento_inActionPerformed(evt);
            }
        });

        botonBuscarAlimento.setText("Buscar");
        botonBuscarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarAlimentoActionPerformed(evt);
            }
        });

        botonAmadirAlimento.setText("Añadir");
        botonAmadirAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAmadirAlimentoActionPerformed(evt);
            }
        });

        borrarAlimentos.setText("Borrar");
        borrarAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarAlimentosActionPerformed(evt);
            }
        });

        menuBorrarComida.setText("Comidas");

        jMenuItem1.setText("Buscar");
        menuBorrarComida.add(jMenuItem1);

        menuAnadirComida.setText("Añadir");
        menuAnadirComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnadirComidaActionPerformed(evt);
            }
        });
        menuBorrarComida.add(menuAnadirComida);

        jMenuItem3.setText("Borrar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuBorrarComida.add(jMenuItem3);

        jMenuBar1.add(menuBorrarComida);

        jMenu2.setText("Alimentos");

        menuBucarAlimento.setText("Buscar");
        menuBucarAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBucarAlimentoActionPerformed(evt);
            }
        });
        jMenu2.add(menuBucarAlimento);

        anadirAlimentosMenu.setText("Añadir");
        anadirAlimentosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirAlimentosMenuActionPerformed(evt);
            }
        });
        jMenu2.add(anadirAlimentosMenu);

        borrarMenuAlimentos.setText("Borrar");
        borrarMenuAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarMenuAlimentosActionPerformed(evt);
            }
        });
        jMenu2.add(borrarMenuAlimentos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menú");

        jMenuItem7.setText("Imprimir");
        jMenu3.add(jMenuItem7);

        nuevoMenu.setText("Nuevo Menú");
        nuevoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuActionPerformed(evt);
            }
        });
        jMenu3.add(nuevoMenu);

        borraralimentoMenu.setText("Borrar Alimento");
        borraralimentoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borraralimentoMenuActionPerformed(evt);
            }
        });
        jMenu3.add(borraralimentoMenu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(112, 112, 112))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botonAnadirMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(nombreAlimento_in))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 70, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(botonBuscarAlimento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botonAmadirAlimento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(borrarAlimentos))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(caloriasAlimento_in)))))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombreAlimento_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAnadirMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(caloriasAlimento_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarAlimento)
                    .addComponent(botonAmadirAlimento)
                    .addComponent(borrarAlimentos))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnadirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirMenuActionPerformed
        CrearMenu.ponerAlimento();
    }//GEN-LAST:event_botonAnadirMenuActionPerformed

    private void nombreAlimento_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAlimento_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAlimento_inActionPerformed

    private void botonBuscarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarAlimentoActionPerformed
        BuscarAlimentos.Buscar();
    }//GEN-LAST:event_botonBuscarAlimentoActionPerformed

    private void botonAmadirAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAmadirAlimentoActionPerformed
        InsertarQuitarAlimentos.insertarAli();
        CargarTablaAlimentos.cargandoTabla();

    }//GEN-LAST:event_botonAmadirAlimentoActionPerformed

    private void tablaComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaComidaMouseClicked
        BDComidas.recargarMenu();
    }//GEN-LAST:event_tablaComidaMouseClicked

    private void borrarAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarAlimentosActionPerformed
        InsertarQuitarAlimentos.QuitarAli();
    }//GEN-LAST:event_borrarAlimentosActionPerformed

    private void menuAnadirComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnadirComidaActionPerformed
        PanelAnadirComida nuevo = new PanelAnadirComida();
        nuevo.setVisible(true);
    }//GEN-LAST:event_menuAnadirComidaActionPerformed

    private void menuBucarAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBucarAlimentoActionPerformed
        PanelBuscarAlimento nuevo = new PanelBuscarAlimento();
        nuevo.setVisible(true);
    }//GEN-LAST:event_menuBucarAlimentoActionPerformed

    private void borraralimentoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borraralimentoMenuActionPerformed
        int selecionadas = tablaMenu.getSelectedRowCount();
        if(selecionadas > 0){
        CrearMenu.quitarAlimento();
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione una comida");
        }
    }//GEN-LAST:event_borraralimentoMenuActionPerformed

    private void anadirAlimentosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirAlimentosMenuActionPerformed
        PanelAnadirAlimento nuevo = new PanelAnadirAlimento();
        nuevo.setVisible(true);
    }//GEN-LAST:event_anadirAlimentosMenuActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       int selecionadas = tablaComida.getSelectedRowCount();
        if(selecionadas > 0){
        try {
            AnadirQuitarComida.quitar();
        } catch (SQLException ex) {
            Logger.getLogger(PanelPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione una comida");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void nuevoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuActionPerformed
        CrearMenu.nuevoMenu();
        tablaAlimentos.clearSelection();
        tablaComida.clearSelection();
    }//GEN-LAST:event_nuevoMenuActionPerformed

    private void borrarMenuAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarMenuAlimentosActionPerformed
                int selecionadas = tablaAlimentos.getSelectedRowCount();
        if(selecionadas > 0){
        InsertarQuitarAlimentos.QuitarAli();
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor seleccione una comida");
        }
    }//GEN-LAST:event_borrarMenuAlimentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem anadirAlimentosMenu;
    public static javax.swing.JButton borrarAlimentos;
    private javax.swing.JMenuItem borrarMenuAlimentos;
    private javax.swing.JMenuItem borraralimentoMenu;
    private javax.swing.JButton botonAmadirAlimento;
    public static javax.swing.JButton botonAnadirMenu;
    private javax.swing.JButton botonBuscarAlimento;
    public static javax.swing.JSpinner caloriasAlimento_in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JMenuItem menuAnadirComida;
    private javax.swing.JMenu menuBorrarComida;
    public static javax.swing.JMenuItem menuBucarAlimento;
    public static javax.swing.JTextField nombreAlimento_in;
    private javax.swing.JMenuItem nuevoMenu;
    public static javax.swing.JTable tablaAlimentos;
    public static javax.swing.JTable tablaComida;
    public static javax.swing.JTable tablaMenu;
    // End of variables declaration//GEN-END:variables
}
